Assignment 4

In [1]:
#Q1
import numpy as np

# i.
c = np.array([1,2,3,4,5])
b = c+2
print(b)

# ii.
d = c*3
print(d)

# iii.
e = c/2
print(e)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [3]:
#Q2
import numpy as np

# a.
arr = np.array([1, 2, 3, 6, 4, 5])
rev = np.flip(arr)
print("Reversed Array:",rev)

# b.
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_freq_val = values[counts == max_count][0]
    indices = np.where(arr == most_freq_val)[0]
    return most_freq_val, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_freq_x, indices_x = most_frequent(x)
print(f"Most frequent value in x: {most_freq_x}, Indices: {indices_x}")

most_freq_y, indices_y = most_frequent(y)
print(f"Most common value in y: {most_freq_y}, Indice: {indices_y}")

Reversed Array: [5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most common value in y: 1, Indice: [0 1 2]


In [4]:
#Q3
import numpy as np

arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Access 1st row, 2nd column: ", arr[0][1])
print("Access 3rd row, 1st column: ", arr[2][0])

Access 1st row, 2nd column:  20
Access 3rd row, 1st column:  70


In [5]:
#Q4
import numpy as np

Mahit = np.linspace(10, 100, 25)
print("Array:", Mahit)
print("Dimensions:", Mahit.ndim)
print("Shape:", Mahit.shape)
print("Total elements:", Mahit.size)
print("Data type:", Mahit.dtype)
print("Total bytes consumed:", Mahit.nbytes)
Mahit_transpose = Mahit.reshape(25, 1)
print("Transpose using reshape():\n", Mahit)
print(Mahit_transpose.shape)

print("Transposing a 1D array using the .T attribute does not change its shape. We need to explicitly create it 2D Array.")
Mahit = Mahit.reshape(1,25)
print("Transpose using T attribute:\n", Mahit.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200
Transpose using reshape():
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25, 1)
Transposing a 1D array using the .T attribute does not change its shape. We need to explicitly create it 2D Array.
Transpose using T attribute:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [6]:
#Q5
ucs420_Mahit = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_Mahit))
print("Median:", np.median(ucs420_Mahit))
print("Max:", np.max(ucs420_Mahit))
print("Min:", np.min(ucs420_Mahit))
print("Unique elements:", np.unique(ucs420_Mahit))
reshaped_ucs420_Mahit = ucs420_Mahit.reshape(4, 3)
print("Reshaped (4x3):\n", reshaped_ucs420_Mahit)
resized_ucs420_Mahit = np.resize(ucs420_Mahit, (2, 3))
print("Resized (2x3):\n", resized_ucs420_Mahit)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3):
 [[10 20 30]
 [40 50 60]]
